export const carDetialsData = [
  {
    title: "Renault Clio 5 Manuel",
    subTitle: "Renault Clio 5 Manuel or Similar",
    mad: "220",
    seats: 4,
    bags: 2,
    door: 4,
    ac: "A/C",
    cylinder: "Diesel",
    system: "manual",
    image: "https://i.ibb.co/JrWhRTb/Renault-Clio-5-Manuel-Final.png",
  },
  {
    title: "Cetroen C-Elysee Manuel",
    subTitle: "Cetroen C-Elysee Manuel or Similar",
    mad: "220",
    seats: 4,
    bags: 2,
    door: 4,
    ac: "A/C",
    cylinder: "Diesel",
    system: "manual",
    image: "https://i.ibb.co/RY4Qv6Q/Cetroen-C-Elysee-Manuel-Final.png",
  },

  {
    title: "Kia Seltos Auto",
    subTitle: "Kia Seltos Auto or Similar",
    mad: "220",
    seats: 4,
    bags: 2,
    door: 4,
    ac: "A/C",
    cylinder: "Diesel",
    system: "Auto",
    image: "https://i.ibb.co/MnTPLsk/Kia-Seltos-Auto-Final-1.png",
  },
  {
    title: "Volkswagen T Roc Auto",
    subTitle: "Volkswagen T Roc Auto or Similar",
    mad: "220",
    seats: 4,
    bags: 2,
    door: 4,
    ac: "A/C",
    cylinder: "Diesel",
    system: "AUTO",
    image: "https://i.ibb.co/w7CYx5g/4.png",
  },
  {
    title: "Toyota Fortuner Auto",
    subTitle: "Toyota Fortuner Auto or Similar",
    mad: "220",
    seats: 4,
    bags: 2,
    door: 4,
    ac: "A/C",
    cylinder: "Diesel",
    system: "Auto",
    image: "https://i.ibb.co/d0hPddp/five.png",
  },
  {
    title: "Toyota Prado Auto",
    subTitle: "Toyota Prado Auto or Similar",
    mad: "220",
    seats: 4,
    bags: 2,
    door: 4,
    ac: "A/C",
    cylinder: "Diesel",
    system: "Auto",
    image: "https://i.ibb.co/mc4k654/six.png",
  },
];
